ProjectDemo/src/ProjectDemo/Controllers/BrowseController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectDemo.Controllers
{
    public class BrowseController : Controller
    {
        public IActionResult Create()
        {
            return View("Index");
        }

        public IActionResult Box()
        {
            return View();
        }

        //public IActionResult Box(string inputs)
        //{
        //    if (inputs == "subdir1")
        //        return View("Sub");
        //    if (inputs == "text")
        //        return View("Txt");
        //    if (inputs == "img")
        //        return View("Img");
        //    else
        //        return View();
        //}

        public IActionResult Sub()
        {
            return View();
        }
        public IActionResult Txt()
        {
            return View();
        }
        public IActionResult Img()
        {
            return View();
        }
    }
}

ProjectDemo/src/ProjectDemo/Views/Browse/Box.cshtml
@{
    ViewBag.Title = "Home Page";
}
<h3>@ViewData["Message"]</h3>

<p>Hello, world!</p>
<p>This is where the normal viewer/browser would be directed.</p>
<p>Content served on this page will include, links to subdirectories (folders), text files, and images.</p>

<p>I haven't gotten the application logic to work, but the overview of it will be this:</p>
<ul>
    <li>1. User will either generate or browse to a link such as hostname.com/Browse/*generated number*/</li>
    <li>2. Browse will handle this number by making a request to the database, treating it as an ID.</li>
    <li>3. Browse controller will serve up the standard 4 page templates, "directory/index", "text content", "image content", "admin"</li>
    <li>4. The database query will return with the appropriate content to fill in the body/contents</li>
    <li>5. Edits in admin mode will be accomplished asynchronously via jquery.</li>

</ul>


<ul>
    <li>
        <div class="col-md-6">
            <a asp-controller="Browse" asp-action="Sub">placeholder subdirectory</a>
        </div>
        <div class="col-md-6">@await Html.PartialAsync("_ButtonPartial")</div>
        <br />
    </li>

    <li>
        <div class="col-md-6">
            <a asp-controller="Browse" asp-action="Txt">placeholder text file</a>
        </div>
        <div class="col-md-6">@await Html.PartialAsync("_ButtonPartial")</div>
        <br />
    </li>
    <li>lalalala sample text list item<br /></li>
    <li>
        <div class="col-md-6">
            <a asp-controller="Browse" asp-action="Img">placeholder image</a>
        </div>
        <div class="col-md-6">@await Html.PartialAsync("_ButtonPartial")</div>
        <br />
    </li>
</ul>@await Html.PartialAsync("_ButtonPartial")</div>

ProjectDemo/src/ProjectDemo/Views/Browse/Img.cshtml
@{
    ViewBag.Title = "Image Page";
}
<div>
    <p>
        image below! (even has a hover text)!
    </p>
    <p>
        <img src="~/images/e3e3e3.png" title="a tasty image for you!" alt="a placeholder 600 by 400">
    </p>
</div>

ProjectDemo/src/ProjectDemo/Views/Browse/Index.cshtml
@{
    ViewBag.Title = "Create DeadDrop";
}
<h3>@ViewData["Message"]</h3>

<p>hello, world!1</p>
<p>This is the landing page for you when you create your own DeadDrop.</p>
<p>(None of this works by the way)</p>

<form action="#" method="post">
    DeadDrop Name:<input type="text" name="boxname" id="boxname"/>
    <br/>
    Admin Password:<input type="password" name="password" id="password"/>
    <br/>
    <input type="submit" value="Create"/>
</form>

ProjectDemo/src/ProjectDemo/Views/Browse/Sub.cshtml
@{
    ViewBag.Title = "Subdirectory";
}

<p>Placeholder stuff!</p>
<p><a href="~/images/placeholder-car1.png">Placeholder link!</a></p>
<p>Placeholder text!</p>

ProjectDemo/src/ProjectDemo/Views/Browse/Txt.cshtml
@{
    ViewBag.Title = "Text Page";
}

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>